import type { Metadata } from "next";
import "./globals.css";

import yekanBakh from "@/fonts/yekanBakh";
import Header from "@/components/template/Header/Header";
import Footer from "@/components/template/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekanBakh.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
